version: '3.8'

services:
  # MongoDB Database - Development version
  mongodb:
    image: mongo:7.0
    container_name: compliance-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: merchantdb_dev
    ports:
      - "27018:27017"  # Different port for dev
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Compliance API Application - Development
  compliance-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: compliance-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/merchantdb_dev?authSource=admin
      JWT_SECRET: dev-jwt-secret-key
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/app/uploads
      - .:/app  # Mount source code for hot reload
      - /app/node_modules  # Exclude node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - compliance-network
    command: npm run dev

  # MongoDB Express - Development
  mongo-express:
    image: mongo-express:1.0.2
    container_name: compliance-mongo-express-dev
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - compliance-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  compliance-network:
    driver: bridge